//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace APPR_POE.Models
{
    using System;
    using System.Collections.Generic;


    public class DisasterReliefModel
    {
        public decimal TotalMonetaryDonations { get; set; }
        public int TotalGoodsReceived { get; set; }
        public List<ActiveDisaster> ActiveDisasters { get; set; }
    }

    public class ActiveDisaster
    {
        public string Name { get; set; }
        public decimal MoneyAllocated { get; set; }
        public int GoodsAllocated { get; set; }
    }

}
