//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPR_POE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonetaryDonation
    {
        public int MonetaryId { get; set; }
        public string Emails { get; set; }
        public string DonatorName { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
